version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "lsaudon"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: "pub"
    directory: "/app"
    schedule:
      interval: "daily"
    reviewers:
      - "lsaudon"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: "pub"
    directory: "/packages/agir_lints"
    schedule:
      interval: "daily"
    reviewers:
      - "lsaudon"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: "pub"
    directory: "/packages/dsfr.dart"
    schedule:
      interval: "daily"
    reviewers:
      - "lsaudon"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: "pub"
    directory: "/packages/dsfr.dart/example"
    schedule:
      interval: "daily"
    reviewers:
      - "lsaudon"
    commit-message:
      prefix: "chore: "
