version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "07:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: pub
    directory: /app
    schedule:
      interval: daily
      time: "07:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: pub
    directory: "/packages/agir_lints"
    schedule:
      interval: monthly
      time: "07:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: pub
    directory: "/packages/dsfr.dart"
    schedule:
      interval: monthly
      time: "07:00"
      timezone: "Europe/Paris"
    reviewers:
      - "lsaudon"
    commit-message:
      prefix: "chore: "
  - package-ecosystem: bundler
    directory: /app/android
    schedule:
      interval: weekly
      time: "07:00"
      timezone: "Europe/Paris"
    groups:
      app-android-bundler:
        patterns:
          - "*"
  - package-ecosystem: gradle
    directory: /app/android/app
    schedule:
      interval: weekly
      time: "07:00"
      timezone: "Europe/Paris"
    groups:
      app-android-app-gradle:
        patterns:
          - "*"
  - package-ecosystem: bundler
    directory: /app/ios
    schedule:
      interval: weekly
      time: "07:00"
      timezone: "Europe/Paris"
    groups:
      app-ios-bundler:
        patterns:
          - "*"