name: melos

ide:
  intellij:
    enabled: false

packages:
  - app
  - packages/**

scripts:
  format_check_diff:
    run: melos exec --diff=origin/main...HEAD --include-dependents dart format $(find . -name '*.dart' -not -name '*.g.dart') --set-exit-if-changed
  analyze_diff:
    run: melos exec --diff=origin/main...HEAD --include-dependents flutter analyze .
  test_diff:
    run: melos exec --diff=origin/main...HEAD --include-dependents flutter test --test-randomize-ordering-seed random