name: melos

ide:
  intellij:
    enabled: false

packages:
  - app
  - packages/**

scripts:
  analyze_diff:
    run: melos exec --diff=origin/main...HEAD --include-dependents flutter analyze .
  format_check_diff:
    run: melos exec --diff=origin/main...HEAD --include-dependents dart format . --set-exit-if-changed
  test_diff:
    run: melos exec --diff=origin/main...HEAD --include-dependents flutter test --test-randomize-ordering-seed random