# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Déployer une nouvelle version dans Firebase App Distributiion"
  lane :development do
    sh("flutter", "clean")
    sh("flutter", "pub", "get")
    sh("flutter", "build", "apk", "--flavor", "development",
                                  "--dart-define-from-file", "env.development.json",
                                  "--build-number", ENV["GITHUB_RUN_NUMBER"])

    # https://firebase.google.com/docs/app-distribution/android/distribute-fastlane
    firebase_app_distribution(
      app: ENV["DEV_APP_ID_ANDROID"],
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      groups: "agir-team",
      release_notes_file: "../release-notes.txt",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-development-release.apk"
    )
  end
end
