# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Déployer une nouvelle version dans Firebase App Distributiion"
  lane :development do
    sh("flutter", "clean")
    sh("flutter", "pub", "get")
    sh("flutter", "build", "appbundle", "--flavor", "development",
                                        "--obfuscate", 
                                        "--split-debug-info=build/app/outputs/symbols")
    # firebase_app_distribution(
    #   groups: "agir-team",
    #   release_notes_file: "../../../release-notes.txt",
    #   service_credentials_file: "./app/google-services.json",
    # )
  end
end
