include: package:jagis_lints/analysis_options.yaml
analyzer:
  exclude: 
    - 'test/features/*_test.dart'
dart_code_metrics:
  exclude:
    unused-files:
      - test/features/step/*.dart
    unused-code:
      - test/features/step/*.dart
  rules:
    - avoid-unnecessary-futures:
        exclude:
          - test/features/step/*.dart
    - avoid-unused-parameters:
        exclude:
          - test/features/step/*.dart