name: agir
description: ""
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  agir_lints:
    path: ../packages/agir_lints
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
