const environmentalPerformanceEmptyData = {
  'bilan_complet': {
    'impact_kg_annee': 2930.02701019,
    'impact_univers': [
      {
        'details': [
          {
            'emoji': '🏛',
            'impact_kg_annee': 1259.4428717769142,
            'label': 'Services publics',
            'pourcentage': null,
            'pourcentage_categorie': 87,
          },
          {
            'emoji': '✉️',
            'impact_kg_annee': 191.4623546094499,
            'label': 'Services marchands',
            'pourcentage': null,
            'pourcentage_categorie': 13,
          },
        ],
        'emoji': '🏛️',
        'impact_kg_annee': 1450.9052263863641,
        'pourcentage': null,
        'univers': 'services_societaux',
        'univers_label': 'Services sociétaux',
      },
      {
        'details': [
          {
            'emoji': '👕',
            'impact_kg_annee': 486.13999999999993,
            'label': 'Textile',
            'pourcentage': null,
            'pourcentage_categorie': 43,
          },
          {
            'emoji': '🛋️',
            'impact_kg_annee': 139.7448484848485,
            'label': 'Ameublement',
            'pourcentage': null,
            'pourcentage_categorie': 12,
          },
          {
            'emoji': '📦',
            'impact_kg_annee': 123.01123396773932,
            'label': 'Autres produits',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '📺',
            'impact_kg_annee': 120.076661030303,
            'label': 'Numérique',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '🎭',
            'impact_kg_annee': 118.99921707433923,
            'label': 'Loisirs',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '🐶',
            'impact_kg_annee': 53.11748316635982,
            'label': 'Animaux',
            'pourcentage': null,
            'pourcentage_categorie': 5,
          },
          {
            'emoji': '🔌',
            'impact_kg_annee': 51.03181818181818,
            'label': 'Electroménager',
            'pourcentage': null,
            'pourcentage_categorie': 5,
          },
          {
            'emoji': '🚬',
            'impact_kg_annee': 7.28,
            'label': 'Tabac',
            'pourcentage': null,
            'pourcentage_categorie': 1,
          },
        ],
        'emoji': '📦',
        'impact_kg_annee': 1125.4872619054079,
        'pourcentage': null,
        'univers': 'consommation',
        'univers_label': 'Mes achats',
      },
      {
        'details': [
          {
            'emoji': '🚘️',
            'impact_kg_annee': 328.2760868517766,
            'label': 'Voiture',
            'pourcentage': null,
            'pourcentage_categorie': 81,
          },
          {
            'emoji': '🚌',
            'impact_kg_annee': 33.7904763482199,
            'label': 'Transports en commun',
            'pourcentage': null,
            'pourcentage_categorie': 8,
          },
          {
            'emoji': '🛵',
            'impact_kg_annee': 23.196418035061875,
            'label': '2 roues',
            'pourcentage': null,
            'pourcentage_categorie': 6,
          },
          {
            'emoji': '⛴',
            'impact_kg_annee': 11.88805068661542,
            'label': 'Ferry',
            'pourcentage': null,
            'pourcentage_categorie': 3,
          },
          {
            'emoji': '🚋',
            'impact_kg_annee': 8.8198802395209,
            'label': 'Train',
            'pourcentage': null,
            'pourcentage_categorie': 2,
          },
          {
            'emoji': '✈️',
            'impact_kg_annee': 0,
            'label': 'Avion',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
          {
            'emoji': '🚲',
            'impact_kg_annee': 0,
            'label': 'Mobilité douce',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
          {
            'emoji': '🏖️',
            'impact_kg_annee': 0,
            'label': 'Vacances',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
        ],
        'emoji': '🚦',
        'impact_kg_annee': 405.9709121611947,
        'pourcentage': null,
        'univers': 'transport',
        'univers_label': 'Mes déplacements',
      },
      {
        'details': [
          {
            'emoji': '🏖',
            'impact_kg_annee': 152.08498652513995,
            'label': 'Vacances',
            'pourcentage': null,
            'pourcentage_categorie': 56,
          },
          {
            'emoji': '❄️',
            'impact_kg_annee': 63.176259272727265,
            'label': 'Climatisation',
            'pourcentage': null,
            'pourcentage_categorie': 23,
          },
          {
            'emoji': '🔥',
            'impact_kg_annee': 25.018392992605325,
            'label': 'Chauffage',
            'pourcentage': null,
            'pourcentage_categorie': 9,
          },
          {
            'emoji': '☘️',
            'impact_kg_annee': 21.45057795454545,
            'label': 'Extérieur',
            'pourcentage': null,
            'pourcentage_categorie': 8,
          },
          {
            'emoji': '🧱',
            'impact_kg_annee': 10.680640520949204,
            'label': 'Construction',
            'pourcentage': null,
            'pourcentage_categorie': 4,
          },
          {
            'emoji': '⚡',
            'impact_kg_annee': 0.67071695602011,
            'label': 'Electricité',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
          {
            'emoji': '🏊',
            'impact_kg_annee': 0,
            'label': 'Piscine',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
        ],
        'emoji': '🏠',
        'impact_kg_annee': 273.0815742219873,
        'pourcentage': null,
        'univers': 'logement',
        'univers_label': 'À la maison',
      },
      {
        'details': [
          {
            'emoji': '🥦',
            'impact_kg_annee': 657.8000000000001,
            'label': 'Fruits & Légumes',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🥐',
            'impact_kg_annee': 394.20000000000005,
            'label': 'Petit déjeuner',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🥤',
            'impact_kg_annee': 225.37310000000002,
            'label': 'Boissons',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🥩',
            'impact_kg_annee': 0,
            'label': 'Viandes',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🐟',
            'impact_kg_annee': 0,
            'label': 'Poissons',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
        ],
        'emoji': '🍴',
        'impact_kg_annee': 0,
        'pourcentage': null,
        'univers': 'alimentation',
        'univers_label': 'En cuisine',
      },
    ],
    'top_3': [
      {
        'emoji': '🚘️',
        'impact_kg_annee': 328.2760868517766,
        'label': 'Voiture',
        'pourcentage': null,
        'pourcentage_categorie': 81,
      },
      {
        'emoji': '✈️',
        'impact_kg_annee': 0,
        'label': 'Avion',
        'pourcentage': null,
        'pourcentage_categorie': 0,
      },
      {
        'emoji': '🛵',
        'impact_kg_annee': 23.196418035061875,
        'label': '2 roues',
        'pourcentage': null,
        'pourcentage_categorie': 6,
      },
    ],
  },
  'bilan_synthese': {
    'impact_alimentation': 'moyen',
    'impact_consommation': 'fort',
    'impact_logement': null,
    'impact_transport': 'faible',
    'liens_bilans_univers': [
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_transport',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728466903/Mobilite_df75aefd09.svg',
        'nombre_total_question': 7,
        'pourcentage_progression': 0,
        'temps_minutes': 5,
        'univers': 'transport',
        'univers_label': 'Mes déplacements',
      },
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_alimentation',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728466523/cuisine_da54797693.svg',
        'nombre_total_question': 5,
        'pourcentage_progression': 20,
        'temps_minutes': 3,
        'univers': 'alimentation',
        'univers_label': 'En cuisine',
      },
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_consommation',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728468852/conso_7522b1950d.svg',
        'nombre_total_question': 7,
        'pourcentage_progression': 0,
        'temps_minutes': 10,
        'univers': 'consommation',
        'univers_label': 'Mes achats',
      },
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_logement',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728468978/maison_80242d91f3.svg',
        'nombre_total_question': 6,
        'pourcentage_progression': 0,
        'temps_minutes': 9,
        'univers': 'logement',
        'univers_label': 'À la maison',
      },
    ],
    'pourcentage_completion_totale': 22,
  },
};

const environmentalPerformancePartialData = {
  'bilan_complet': {
    'impact_kg_annee': 2930.02701019,
    'impact_univers': [
      {
        'details': [
          {
            'emoji': '🏛',
            'impact_kg_annee': 1259.4428717769142,
            'label': 'Services publics',
            'pourcentage': null,
            'pourcentage_categorie': 87,
          },
          {
            'emoji': '✉️',
            'impact_kg_annee': 191.4623546094499,
            'label': 'Services marchands',
            'pourcentage': null,
            'pourcentage_categorie': 13,
          },
        ],
        'emoji': '🏛️',
        'impact_kg_annee': 1450.9052263863641,
        'pourcentage': null,
        'univers': 'services_societaux',
        'univers_label': 'Services sociétaux',
      },
      {
        'details': [
          {
            'emoji': '👕',
            'impact_kg_annee': 486.13999999999993,
            'label': 'Textile',
            'pourcentage': null,
            'pourcentage_categorie': 43,
          },
          {
            'emoji': '🛋️',
            'impact_kg_annee': 139.7448484848485,
            'label': 'Ameublement',
            'pourcentage': null,
            'pourcentage_categorie': 12,
          },
          {
            'emoji': '📦',
            'impact_kg_annee': 123.01123396773932,
            'label': 'Autres produits',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '📺',
            'impact_kg_annee': 120.076661030303,
            'label': 'Numérique',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '🎭',
            'impact_kg_annee': 118.99921707433923,
            'label': 'Loisirs',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '🐶',
            'impact_kg_annee': 53.11748316635982,
            'label': 'Animaux',
            'pourcentage': null,
            'pourcentage_categorie': 5,
          },
          {
            'emoji': '🔌',
            'impact_kg_annee': 51.03181818181818,
            'label': 'Electroménager',
            'pourcentage': null,
            'pourcentage_categorie': 5,
          },
          {
            'emoji': '🚬',
            'impact_kg_annee': 7.28,
            'label': 'Tabac',
            'pourcentage': null,
            'pourcentage_categorie': 1,
          },
        ],
        'emoji': '📦',
        'impact_kg_annee': 1125.4872619054079,
        'pourcentage': null,
        'univers': 'consommation',
        'univers_label': 'Mes achats',
      },
      {
        'details': [
          {
            'emoji': '🚘️',
            'impact_kg_annee': 328.2760868517766,
            'label': 'Voiture',
            'pourcentage': null,
            'pourcentage_categorie': 81,
          },
          {
            'emoji': '🚌',
            'impact_kg_annee': 33.7904763482199,
            'label': 'Transports en commun',
            'pourcentage': null,
            'pourcentage_categorie': 8,
          },
          {
            'emoji': '🛵',
            'impact_kg_annee': 23.196418035061875,
            'label': '2 roues',
            'pourcentage': null,
            'pourcentage_categorie': 6,
          },
          {
            'emoji': '⛴',
            'impact_kg_annee': 11.88805068661542,
            'label': 'Ferry',
            'pourcentage': null,
            'pourcentage_categorie': 3,
          },
          {
            'emoji': '🚋',
            'impact_kg_annee': 8.8198802395209,
            'label': 'Train',
            'pourcentage': null,
            'pourcentage_categorie': 2,
          },
          {
            'emoji': '✈️',
            'impact_kg_annee': 0,
            'label': 'Avion',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
          {
            'emoji': '🚲',
            'impact_kg_annee': 0,
            'label': 'Mobilité douce',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
          {
            'emoji': '🏖️',
            'impact_kg_annee': 0,
            'label': 'Vacances',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
        ],
        'emoji': '🚦',
        'impact_kg_annee': 405.9709121611947,
        'pourcentage': null,
        'univers': 'transport',
        'univers_label': 'Mes déplacements',
      },
      {
        'details': [
          {
            'emoji': '🏖',
            'impact_kg_annee': 152.08498652513995,
            'label': 'Vacances',
            'pourcentage': null,
            'pourcentage_categorie': 56,
          },
          {
            'emoji': '❄️',
            'impact_kg_annee': 63.176259272727265,
            'label': 'Climatisation',
            'pourcentage': null,
            'pourcentage_categorie': 23,
          },
          {
            'emoji': '🔥',
            'impact_kg_annee': 25.018392992605325,
            'label': 'Chauffage',
            'pourcentage': null,
            'pourcentage_categorie': 9,
          },
          {
            'emoji': '☘️',
            'impact_kg_annee': 21.45057795454545,
            'label': 'Extérieur',
            'pourcentage': null,
            'pourcentage_categorie': 8,
          },
          {
            'emoji': '🧱',
            'impact_kg_annee': 10.680640520949204,
            'label': 'Construction',
            'pourcentage': null,
            'pourcentage_categorie': 4,
          },
          {
            'emoji': '⚡',
            'impact_kg_annee': 0.67071695602011,
            'label': 'Electricité',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
          {
            'emoji': '🏊',
            'impact_kg_annee': 0,
            'label': 'Piscine',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
        ],
        'emoji': '🏠',
        'impact_kg_annee': 273.0815742219873,
        'pourcentage': null,
        'univers': 'logement',
        'univers_label': 'À la maison',
      },
      {
        'details': [
          {
            'emoji': '🥦',
            'impact_kg_annee': 657.8000000000001,
            'label': 'Fruits & Légumes',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🥐',
            'impact_kg_annee': 394.20000000000005,
            'label': 'Petit déjeuner',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🥤',
            'impact_kg_annee': 225.37310000000002,
            'label': 'Boissons',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🥩',
            'impact_kg_annee': 0,
            'label': 'Viandes',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🐟',
            'impact_kg_annee': 0,
            'label': 'Poissons',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
        ],
        'emoji': '🍴',
        'impact_kg_annee': 0,
        'pourcentage': null,
        'univers': 'alimentation',
        'univers_label': 'En cuisine',
      },
    ],
    'top_3': [
      {
        'emoji': '🚘️',
        'impact_kg_annee': 328.2760868517766,
        'label': 'Voiture',
        'pourcentage': null,
        'pourcentage_categorie': 81,
      },
      {
        'emoji': '✈️',
        'impact_kg_annee': 0,
        'label': 'Avion',
        'pourcentage': null,
        'pourcentage_categorie': 0,
      },
      {
        'emoji': '🛵',
        'impact_kg_annee': 23.196418035061875,
        'label': '2 roues',
        'pourcentage': null,
        'pourcentage_categorie': 6,
      },
    ],
  },
  'bilan_synthese': {
    'impact_alimentation': 'moyen',
    'impact_consommation': 'fort',
    'impact_logement': null,
    'impact_transport': 'faible',
    'liens_bilans_univers': [
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_transport',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728466903/Mobilite_df75aefd09.svg',
        'nombre_total_question': 7,
        'pourcentage_progression': 0,
        'temps_minutes': 5,
        'univers': 'transport',
        'univers_label': 'Mes déplacements',
      },
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_alimentation',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728466523/cuisine_da54797693.svg',
        'nombre_total_question': 5,
        'pourcentage_progression': 20,
        'temps_minutes': 3,
        'univers': 'alimentation',
        'univers_label': 'En cuisine',
      },
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_consommation',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728468852/conso_7522b1950d.svg',
        'nombre_total_question': 8,
        'pourcentage_progression': 0,
        'temps_minutes': 10,
        'univers': 'consommation',
        'univers_label': 'Mes achats',
      },
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_logement',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728468978/maison_80242d91f3.svg',
        'nombre_total_question': 6,
        'pourcentage_progression': 0,
        'temps_minutes': 9,
        'univers': 'logement',
        'univers_label': 'À la maison',
      },
    ],
    'pourcentage_completion_totale': 23,
  },
};

const environmentalPerformanceFullData = {
  'bilan_complet': {
    'impact_kg_annee': 2930.02701019,
    'impact_univers': [
      {
        'details': [
          {
            'emoji': '🏛',
            'impact_kg_annee': 1259.4428717769142,
            'label': 'Services publics',
            'pourcentage': null,
            'pourcentage_categorie': 87,
          },
          {
            'emoji': '✉️',
            'impact_kg_annee': 191.4623546094499,
            'label': 'Services marchands',
            'pourcentage': null,
            'pourcentage_categorie': 13,
          },
        ],
        'emoji': '🏛️',
        'impact_kg_annee': 1450.9052263863641,
        'pourcentage': null,
        'univers': 'services_societaux',
        'univers_label': 'Services sociétaux',
      },
      {
        'details': [
          {
            'emoji': '👕',
            'impact_kg_annee': 486.13999999999993,
            'label': 'Textile',
            'pourcentage': null,
            'pourcentage_categorie': 43,
          },
          {
            'emoji': '🛋️',
            'impact_kg_annee': 139.7448484848485,
            'label': 'Ameublement',
            'pourcentage': null,
            'pourcentage_categorie': 12,
          },
          {
            'emoji': '📦',
            'impact_kg_annee': 123.01123396773932,
            'label': 'Autres produits',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '📺',
            'impact_kg_annee': 120.076661030303,
            'label': 'Numérique',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '🎭',
            'impact_kg_annee': 118.99921707433923,
            'label': 'Loisirs',
            'pourcentage': null,
            'pourcentage_categorie': 11,
          },
          {
            'emoji': '🐶',
            'impact_kg_annee': 53.11748316635982,
            'label': 'Animaux',
            'pourcentage': null,
            'pourcentage_categorie': 5,
          },
          {
            'emoji': '🔌',
            'impact_kg_annee': 51.03181818181818,
            'label': 'Electroménager',
            'pourcentage': null,
            'pourcentage_categorie': 5,
          },
          {
            'emoji': '🚬',
            'impact_kg_annee': 7.28,
            'label': 'Tabac',
            'pourcentage': null,
            'pourcentage_categorie': 1,
          },
        ],
        'emoji': '📦',
        'impact_kg_annee': 1125.4872619054079,
        'pourcentage': null,
        'univers': 'consommation',
        'univers_label': 'Mes achats',
      },
      {
        'details': [
          {
            'emoji': '🚘️',
            'impact_kg_annee': 328.2760868517766,
            'label': 'Voiture',
            'pourcentage': null,
            'pourcentage_categorie': 81,
          },
          {
            'emoji': '🚌',
            'impact_kg_annee': 33.7904763482199,
            'label': 'Transports en commun',
            'pourcentage': null,
            'pourcentage_categorie': 8,
          },
          {
            'emoji': '🛵',
            'impact_kg_annee': 23.196418035061875,
            'label': '2 roues',
            'pourcentage': null,
            'pourcentage_categorie': 6,
          },
          {
            'emoji': '⛴',
            'impact_kg_annee': 11.88805068661542,
            'label': 'Ferry',
            'pourcentage': null,
            'pourcentage_categorie': 3,
          },
          {
            'emoji': '🚋',
            'impact_kg_annee': 8.8198802395209,
            'label': 'Train',
            'pourcentage': null,
            'pourcentage_categorie': 2,
          },
          {
            'emoji': '✈️',
            'impact_kg_annee': 0,
            'label': 'Avion',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
          {
            'emoji': '🚲',
            'impact_kg_annee': 0,
            'label': 'Mobilité douce',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
          {
            'emoji': '🏖️',
            'impact_kg_annee': 0,
            'label': 'Vacances',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
        ],
        'emoji': '🚦',
        'impact_kg_annee': 405.9709121611947,
        'pourcentage': null,
        'univers': 'transport',
        'univers_label': 'Mes déplacements',
      },
      {
        'details': [
          {
            'emoji': '🏖',
            'impact_kg_annee': 152.08498652513995,
            'label': 'Vacances',
            'pourcentage': null,
            'pourcentage_categorie': 56,
          },
          {
            'emoji': '❄️',
            'impact_kg_annee': 63.176259272727265,
            'label': 'Climatisation',
            'pourcentage': null,
            'pourcentage_categorie': 23,
          },
          {
            'emoji': '🔥',
            'impact_kg_annee': 25.018392992605325,
            'label': 'Chauffage',
            'pourcentage': null,
            'pourcentage_categorie': 9,
          },
          {
            'emoji': '☘️',
            'impact_kg_annee': 21.45057795454545,
            'label': 'Extérieur',
            'pourcentage': null,
            'pourcentage_categorie': 8,
          },
          {
            'emoji': '🧱',
            'impact_kg_annee': 10.680640520949204,
            'label': 'Construction',
            'pourcentage': null,
            'pourcentage_categorie': 4,
          },
          {
            'emoji': '⚡',
            'impact_kg_annee': 0.67071695602011,
            'label': 'Electricité',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
          {
            'emoji': '🏊',
            'impact_kg_annee': 0,
            'label': 'Piscine',
            'pourcentage': null,
            'pourcentage_categorie': 0,
          },
        ],
        'emoji': '🏠',
        'impact_kg_annee': 273.0815742219873,
        'pourcentage': null,
        'univers': 'logement',
        'univers_label': 'À la maison',
      },
      {
        'details': [
          {
            'emoji': '🥦',
            'impact_kg_annee': 657.8000000000001,
            'label': 'Fruits & Légumes',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🥐',
            'impact_kg_annee': 394.20000000000005,
            'label': 'Petit déjeuner',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🥤',
            'impact_kg_annee': 225.37310000000002,
            'label': 'Boissons',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🥩',
            'impact_kg_annee': 0,
            'label': 'Viandes',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
          {
            'emoji': '🐟',
            'impact_kg_annee': 0,
            'label': 'Poissons',
            'pourcentage': null,
            'pourcentage_categorie': null,
          },
        ],
        'emoji': '🍴',
        'impact_kg_annee': 0,
        'pourcentage': null,
        'univers': 'alimentation',
        'univers_label': 'En cuisine',
      },
    ],
    'top_3': [
      {
        'emoji': '🚘️',
        'impact_kg_annee': 328.2760868517766,
        'label': 'Voiture',
        'pourcentage': null,
        'pourcentage_categorie': 81,
      },
      {
        'emoji': '✈️',
        'impact_kg_annee': 0,
        'label': 'Avion',
        'pourcentage': null,
        'pourcentage_categorie': 0,
      },
      {
        'emoji': '🛵',
        'impact_kg_annee': 23.196418035061875,
        'label': '2 roues',
        'pourcentage': null,
        'pourcentage_categorie': 6,
      },
    ],
  },
  'bilan_synthese': {
    'impact_alimentation': 'moyen',
    'impact_consommation': null,
    'impact_logement': null,
    'impact_transport': 'faible',
    'liens_bilans_univers': [
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_transport',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728466903/Mobilite_df75aefd09.svg',
        'nombre_total_question': 7,
        'pourcentage_progression': 0,
        'temps_minutes': 5,
        'univers': 'transport',
        'univers_label': 'Mes déplacements',
      },
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_alimentation',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728466523/cuisine_da54797693.svg',
        'nombre_total_question': 5,
        'pourcentage_progression': 20,
        'temps_minutes': 3,
        'univers': 'alimentation',
        'univers_label': 'En cuisine',
      },
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_consommation',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728468852/conso_7522b1950d.svg',
        'nombre_total_question': 7,
        'pourcentage_progression': 0,
        'temps_minutes': 10,
        'univers': 'consommation',
        'univers_label': 'Mes achats',
      },
      {
        'id_enchainement_kyc': 'ENCHAINEMENT_KYC_bilan_logement',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1728468978/maison_80242d91f3.svg',
        'nombre_total_question': 6,
        'pourcentage_progression': 0,
        'temps_minutes': 9,
        'univers': 'logement',
        'univers_label': 'À la maison',
      },
    ],
    'pourcentage_completion_totale': 100,
  },
};

const miniBilan = [
  {
    'categorie': 'mission',
    'id': 'KYC_transport_voiture_km',
    'is_NGC': true,
    'points': 5,
    'question': "Quelle distance parcourez-vous à l'année en voiture ? (en km)",
    'reponse': <String>[],
    'reponses_possibles': <String>[],
    'thematique': 'transport',
    'type': 'entier',
  },
  {
    'categorie': 'mission',
    'id': 'KYC_transport_avion_3_annees',
    'is_NGC': true,
    'points': 5,
    'question':
        "Avez-vous pris l'avion au moins une fois ces 3 dernières années ?",
    'reponse': <String>[],
    'reponses_possibles': <String>['Oui', 'Non', 'Je ne sais pas'],
    'thematique': 'transport',
    'type': 'choix_unique',
  },
  {
    'categorie': 'mission',
    'id': 'MOSAIC_CHAUFFAGE',
    'is_answered': false,
    'points': 5,
    'reponses': <Map<String, dynamic>>[
      {
        'boolean_value': false,
        'code': 'KYC_chauffage_bois',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1726497242/Screenshot_2024_09_16_at_16_22_55_4fcb2d1a5b.png',
        'label': 'Bois',
      },
      {
        'boolean_value': false,
        'code': 'KYC_chauffage_fioul',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1726497260/Screenshot_2024_09_16_at_16_23_05_4103677680.png',
        'label': 'Fioul',
      },
      {
        'boolean_value': false,
        'code': 'KYC_chauffage_gaz',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1726497275/Screenshot_2024_09_16_at_16_23_19_1084c4bd18.png',
        'label': 'Gaz',
      },
      {
        'boolean_value': false,
        'code': 'KYC_chauffage_elec',
        'image_url':
            'https://res.cloudinary.com/dq023imd8/image/upload/v1727275914/Screenshot_2024_09_25_at_16_51_08_876426bef9.png',
        'label': 'Électricité',
      },
    ],
    'titre': 'Quels modes de chauffage existent chez vous ?',
    'type': 'mosaic_boolean',
  },
  {
    'categorie': 'mission',
    'id': 'KYC_superficie',
    'is_NGC': true,
    'points': 5,
    'question': 'Quelle est la superficie de votre logement ? (en m2) ',
    'reponse': <String>[],
    'reponses_possibles': <String>[],
    'thematique': 'logement',
    'type': 'entier',
  },
  {
    'categorie': 'mission',
    'id': 'KYC_menage',
    'is_NGC': true,
    'points': 5,
    'question': 'Combien êtes-vous dans votre logement (vous inclus) ?',
    'reponse': <String>[],
    'reponses_possibles': <String>[],
    'thematique': 'logement',
    'type': 'entier',
  },
  {
    'categorie': 'mission',
    'id': 'KYC_alimentation_regime',
    'is_NGC': false,
    'points': 5,
    'question': 'Quel est votre régime alimentaire moyen ?',
    'reponse': <String>[],
    'reponses_possibles': <String>[
      'Végétalien',
      'Végétarien',
      'Peu de viande',
      'Viande chaque jour',
    ],
    'thematique': 'alimentation',
    'type': 'choix_unique',
  },
  {
    'categorie': 'mission',
    'id': 'KYC_consommation_type_consommateur',
    'is_NGC': false,
    'points': 5,
    'question': 'Quel genre de consommateur êtes vous ?',
    'reponse': <String>[],
    'reponses_possibles': <String>[
      "Je n'achète presque jamais, et rarement neuf",
      "Je chine : l'essentiel de mes achats, c'est de la seconde main",
      "J'achète raisonnablement selon mes besoins et me fais plaisir de temps en temps",
      "J'adore le shopping : il me faut absolument le dernier téléphone ou le dernier t-shirt qui vient de sortir",
    ],
    'thematique': 'consommation',
    'type': 'choix_unique',
  },
];
