import 'package:flutter_test/flutter_test.dart';

/// Usage: A notification token is generated by Firebase for this device
Future<void> aNotificationTokenIsGeneratedByFirebaseForThisDevice(final WidgetTester tester) async {}
