name: dsfr_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: 3.4.4
  flutter: 3.22.3

dependencies:
  cupertino_icons: 1.0.8
  dsfr:
    path: ../
  flutter:
    sdk: flutter
dev_dependencies:
  agir_lints:
    path: ../../agir_lints
  dart_code_metrics_presets: 2.14.0
flutter:
  uses-material-design: true