# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Déployer une nouvelle version dans Firebase App Distributiion"
  lane :development do
    sh("flutter", "clean")
    sh("flutter", "pub", "get")
    sh("flutter", "build", "ipa", "--obfuscate", 
                                  "--split-debug-info=build/ios/symbols", 
                                  "--export-options-plist", "ios/ExportOptions.plist")
    # firebase_app_distribution(
    #   groups: "agir-team",
    #   release_notes_file: "../../../release-notes.txt",
    #   googleservice_info_plist_path: "./Runner/GoogleService-Info.plist",
    # )
  end
end
